# Generated by Django 4.1.5 on 2023-05-10 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_key', models.CharField(max_length=10)),
                ('class_name', models.CharField(max_length=50)),
                ('top_level', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=255, null=True)),
                ('examples', models.CharField(max_length=255, null=True, blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExitInfoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=50)),
                ('answer', models.CharField(blank=True, default='', max_length=750, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
            ],
        ),
        migrations.CreateModel(
            name='TestSound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sound_id', models.CharField(max_length=50)),
                ('sound_class', models.CharField(max_length=50)),
                ('sound_group', models.IntegerField()),
                ('sound_difficulty', models.CharField(max_length=3)),
                ('sound_name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='UserDetailsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=50)),
                ('ip_address', models.GenericIPAddressField(null=True)),
                ('q1', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='', max_length=50)),
                ('q2', models.IntegerField(blank=True, null=True)),
                ('q3', models.CharField(choices=[('1', 'No experience'), ('2', 'Experience as a hobbyist'), ('3', 'Experience as a professional')], default='', max_length=50)),
                ('q4', models.CharField(choices=[('1', 'No experience'), ('2', 'Experience as a hobbyist'), ('3', 'Experience as a professional')], default='', max_length=50)),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
            ],
        ),
        migrations.CreateModel(
            name='SoundAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=50)),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('chosen_class', models.CharField(default='', max_length=15)),
                ('confidence', models.IntegerField(choices=[(1, 'Very Unconfident'), (2, 'Unconfident'), (3, 'Neutral'), (4, 'Confident'), (5, 'Very Confident')], default='')),
                ('test_sound', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classurvey.testsound')),
            ],
        ),
    ]
