# Generated by Django 4.1.5 on 2023-05-10 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classurvey', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soundanswer',
            name='chosen_class',
            field=models.CharField(choices=[('m-sp', 'Solo percussion'), ('m-si', 'Solo instrument'), ('m-m', 'Multiple instruments'), ('m-other', 'Other'), ('i-p', 'Percussion'), ('i-s', 'String'), ('i-w', 'Wind'), ('i-k', 'Keyboard'), ('i-e', 'Synths / Electronic'), ('i-other', 'Other'), ('sp-s', 'Solo'), ('sp-c', 'Conversation / Crowd'), ('sp-p', 'Processed / Synthetic'), ('sp-other', 'Other'), ('fx-o', 'Daily objects / House appliances'), ('fx-v', 'Vehicles'), ('fx-m', 'Other mechanisms, engines, machines'), ('fx-h', 'Human sounds and actions'), ('fx-a', 'Animals'), ('fx-n', 'Natural elements and explosions'), ('fx-d', 'Design'), ('fx-ex', 'Experimental'), ('fx-el', 'Electronic'), ('fx-other', 'Other'), ('ss-n', 'Nature'), ('ss-i', 'Indoors'), ('ss-u', 'Urban'), ('ss-s', 'Synthetic / Artificial'), ('ss-other', 'Other')], default='', max_length=15),
        ),
    ]
