# Generated by Django 4.1.7 on 2023-07-07 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classurvey', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('top_level_name', models.CharField(max_length=10)),
                ('top_level_description', models.CharField(max_length=255)),
            ],
        ),
    ]
