# Generated by Django 4.1.8 on 2023-07-07 14:49

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('classurvey', '0002_toplevel'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetailsmodel',
            name='q5',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('mr', 'Music or radio production'), ('f', 'Film making, game development, video creation'), ('s', 'Sound design'), ('mc', 'Music composition'), ('ex', 'Exploratory sound art, audio installations'), ('ed', 'Education'), ('r', 'Research')], default='', max_length=255),
        ),
    ]
